Ferlab-Ste-Justine/clin-environments

- qa/spark-jobs/variant-etl/configs.yml
- qa/spark-jobs/variant-etl/job.yml
- qa/spark-jobs/variant-etl/kustomization.yaml
> feat: Ferlab-Ste-Justine/clin-project#396 Added variants etl job

- .github/workflows/commit_lint.yml
> feat: Ferlab-Ste-Justine/clin-project#390 Added commit lint pipeline

- qa/fhir-server/ingresses.yml
- qa/frontend/ingresses.yml
- qa/proxy-api/ingresses.yml
Switched to temporary certificate
> fix: #443 Switched to temporary certificate

- qa/fhir-server/ingresses.yml
- qa/frontend/ingresses.yml
- qa/proxy-api/ingresses.yml
Revert -> Switched to temporary certificate
> fix: #443 Revert -> Switched to temporary certificate

- qa/kustomization.yaml
Added fhir-console to global orchestration
> fix: #376 Added fhir-console to global orchestration

- qa/fhir-console/ingresses.yml
> fix: #376 Fixed duplicate ingress name

- common/fhir-console/services.yml
Added session affinity to fhir-console service
> fix: #376 Added session affinity to fhir-console service

- common/fhir-console/deployments.yml
- common/fhir-console/services.yml
Set fhir console to one replica
> fix: #376 Set fhir console to one replica

- qa/keycloak/jobs.yml
- qa/keycloak/kustomization.yaml
- qa/kustomization.yaml
Added clin keycloak config automation
> feat: #629 Added clin keycloak config automation

- qa/keycloak/jobs.yml
Added timeout and no retries for keycloak configuration job
> fix: #712 Added timeout and no retries for keycloak configuration job

- .github/workflows/validate.yml
- .gitmodules
- dev/.flux.yaml
- dev/certificate/certificate.yml
- dev/certificate/issuers.yml
- dev/certificate/kustomization.yaml
- dev/kustomization.yaml
Added clin dev environment with certificate
> feat: #621 Added clin dev environment with certificate

- qa/fhir-server/backups/backup.yml
- qa/fhir-server/backups/kustomization.yaml
- qa/fhir-server/backups/prune-backups.yml
- qa/fhir-server/kustomization.yaml
> feat: #621 Added fhir db backup

- qa/kustomization.yaml
> Temporarly disable keycloak configuration

- qa/kustomization.yaml
> #859 Re-enable keycloak automation

- qa/fhir-server/configmaps.yml
Also increased jvm memory consumption
> fix: #849 Also increased jvm memory consumption

- qa/fhir-server/backups/backup.yml
- qa/fhir-server/backups/prune-backups.yml
Updated fhir backup to portable format
> feat: #298 Updated fhir backup to portable format

- .github/workflows/commit_lint.yml
Changed commit lint to new convention
> feat: CLIN-32 Changed commit lint to new convention

- qa/kustomization.yaml
Re-enabled keycloak autoconfig
> feat: CLIN-41 Re-enabled keycloak autoconfig

- .github/workflows/validate.yml
- .gitmodules
- staging/certificate/certificate.yml
- staging/certificate/issuers.yml
- staging/certificate/kustomization.yaml
- staging/kustomization.yaml
Added staging environment with certificate
> feat: CLIN-52 Added staging environment with certificate

- staging/certificate/kustomization.yaml
Fixed staging certificate namespace
> fix: CLIN-52 Fixed staging certificate namespace

- staging/git-autosync/configmaps.yml
- staging/git-autosync/daemonsets.yml
- staging/git-autosync/kustomization.yaml
- staging/kustomization.yaml
Added git-autosync service for keycloak clin theme
> feat: CLIN-52 Added git-autosync service for keycloak clin theme

- staging/keycloak/kustomization.yaml
- staging/kustomization.yaml
Added keycloak to main orchestration
> fix: CLIN-52 Added keycloak to main orchestration

- dev/fhir-server/deployments.yml
> feat: CLIN-57 Added keycloak fhir secret

- qa/fhir-server/deployments.yml
> feat: CLIN-57 Added fhir secret to qa

- qa/keycloak/jobs.yml
Adapted qa keycloak config job use the qa path in the repo
> feat: CLIN-58 Adapted qa keycloak config job use the qa path in the repo

- staging/fhir-server/configmaps.yml
- staging/fhir-server/deployments.yml
- staging/fhir-server/ingresses.yml
- staging/fhir-server/kustomization.yaml
- staging/kustomization.yaml
> feat: #370 Added clin fhir orchestration

- staging/fhir-server/configmaps.yml
> fix: CLIN-52 Fixed postgres connection

- staging/fhir-console/configs.yml
- staging/fhir-console/deployments.yml
- staging/fhir-console/ingresses.yml
- staging/fhir-console/kustomization.yaml
- staging/kustomization.yaml
Added fhir console orchestration
> feat: CLIN-52 Added fhir console orchestration

- staging/proxy-api/configmaps.yml
- staging/proxy-api/deployments.yml
- staging/proxy-api/es-migration/aliases.json
- staging/proxy-api/es-migration/kustomization.yaml
- staging/proxy-api/es-migration/migrate.sh
- staging/proxy-api/es-migration/migration.yml
- staging/proxy-api/ingresses.yml
- staging/proxy-api/kustomization.yaml
Orchestrated clin proxy services in staging
> feat: CLIN-52 Orchestrated clin proxy services in staging

- staging/ferload/configmaps.yml
- staging/ferload/deployments.yml
- staging/ferload/ingresses.yml
- staging/ferload/kustomization.yaml
- staging/kustomization.yaml
Added ferload service orchestration
> feat: CLIN-52 Added ferload service orchestration

- qa/frontend/deployments.yml
Added variables to orchestration frontend
> feat: CLIN-52 Added variables to orchestration frontend

- staging/frontend/deployments.yml
- staging/frontend/ingresses.yml
- staging/frontend/kustomization.yaml
- staging/kustomization.yaml
> feat: CLIN-52 Added frontend orchestration

- staging/flux-patch.yaml
> fix: CLIN-52 Fixed patch file

- staging/ferload/deployments.yml
- staging/fhir-console/deployments.yml
- staging/fhir-server/deployments.yml
- staging/frontend/deployments.yml
- staging/git-autosync/daemonsets.yml
- staging/proxy-api/deployments.yml
Corrected tag for flux semver orchestrations in staging
> feat: CLIN-52 Corrected tag for flux semver orchestrations in staging

- qa/keycloak/kustomization.yaml
> feat: CLIN-41 Disabled keycloak autoconfig

- staging/proxy-api/es-migration/migrate-data.sh
Missing shebang in migration script
> fix: CLIN-73 Missing shebang in migration script

- qa/frontend/ingresses.yml
- staging/frontend/ingresses.yml
Fixed tls redirection problem for frontend
> fix: CLIN-79 Fixed tls redirection problem for frontend

- qa/fhir-server/ingresses.yml
- staging/fhir-server/ingresses.yml
Increased response timeout for fhir server
> fix: CLIN-185 Increased response timeout for fhir server

- qa/fhir-server/ingresses.yml
- staging/fhir-server/ingresses.yml
Fixed errorous notation for fhir timeouts
> fix: CLIN-185 Fixed errorous notation for fhir timeouts

- qa/spark-jobs/legacy-containers-migration/job.yml
- qa/spark-jobs/legacy-containers-migration/kustomization.yaml
- qa/spark-jobs/legacy-containers-migration/migrate.sh
Added job to migrate legacy spark containers content
> feat: CLIN-194 Added job to migrate legacy spark containers content

- qa/fhir-server/configmaps.yml
Reverts Ferlab-Ste-Justine/clin-environments#107
> Revert "feat: CLIN-194 Disable authorization in kustomization.yaml"

- qa/flux-patch.yaml
Removing fhir-server from patch file
> feat: #298 Removing fhir-server from patch file

- qa/fhir-server/backups/backup.yml
Put qa fhir backups back to every 4 hours
> feat: #298 Put qa fhir backups back to every 4 hours

- qa/kustomization.yaml
- staging/kustomization.yaml
> feat: #425 Disabled clin in cqdg cluster

- qa/proxy-api/configmaps.yml
Missed one of the keycloak urls
> fix: #425 Missed one of the keycloak urls

- qa/keycloak/kustomization.yaml
Enabled keycloak auto-configuration
> feat: #425 Enabled keycloak auto-configuration

- qa/hive-metastore/deployments.yml
- staging/hive-metastore/deployments.yml
> fix: #425 Fixed xml encoding probleme

- qa/certificate/certificate.yml
- qa/kustomization.yaml
- qa/notebook/ingress.yml
- qa/notebook/kustomization.yaml
- staging/certificate/certificate.yml
- staging/kustomization.yaml
- staging/notebook/ingress.yml
- staging/notebook/kustomization.yaml
> feat: #425 Added zeppelin access

- staging/hive-metastore/service.yml
Changed staging hive nodeport port to avoid clashing with qa
> fix: #425 Changed staging hive nodeport port to avoid clashing with qa

- qa/notebook/ingress.yml
- staging/notebook/ingress.yml
Fixed bad notebook ingress domains
> fix: #425 Fixed bad notebook ingress domains

- qa/certificate/issuers.yml
- staging/certificate/issuers.yml
Fixed letsencrypt orchestration across qa/staging
> fix: #425 Fixed letsencrypt orchestration across qa/staging

- common/ferload/configmaps/kustomization.yaml
- common/fhir-server/configmaps/kustomization.yaml
- dev/fhir-server/deployments.yml
- qa/ferload/configmaps.yml
- qa/ferload/deployments.yml
- qa/fhir-server/configmaps.yml
- qa/fhir-server/deployments.yml
- staging/ferload/configmaps.yml
- staging/ferload/deployments.yml
- staging/fhir-server/deployments.yml
> feat: CLIN-207 - add ferload download envs

- qa/fluxcd/arranger.yml
- qa/fluxcd/ferload.yml
- qa/fluxcd/fhir-console.yml
- qa/fluxcd/fhir-server.yml
- qa/fluxcd/frontend.yml
- qa/fluxcd/git-autosync.yml
- qa/fluxcd/hive-metastore.yml
- qa/fluxcd/keycloak.yml
- qa/fluxcd/kustomization.yaml
- qa/fluxcd/proxy-api.yml
- staging/fluxcd/arranger.yml
- staging/fluxcd/ferload.yml
- staging/fluxcd/fhir-console.yml
- staging/fluxcd/fhir-server.yml
- staging/fluxcd/frontend.yml
- staging/fluxcd/git-autosync.yml
- staging/fluxcd/hive-metastore.yml
- staging/fluxcd/keycloak.yml
- staging/fluxcd/proxy-api.yml
> fix: CLIN-405 Fixed fluxcd namespaces

- qa/apps/frontend/deployments.yml
- staging/apps/frontend/deployments.yml
Two new env vars for front-end Zeplin + Fhir console footer urls
> feat: CLIN-406 - zeplin + fhir footer urls

- kustomization.yaml
Enabled fluxcd v2 on the staging environment
> feat: CLIN-405 Enabled fluxcd v2 on the staging environment

- qa/fluxcd/frontend.yml
- staging/fluxcd/frontend.yml
Fixed clin frontend image name
> fix: CLIN-421 Fixed clin frontend image name

- qa/fluxcd/fhir-server.yml
- staging/fluxcd/fhir-server.yml
> fix: CLIN-421 Fixed fhir server image name

- qa/apps/certificate/certificate.yml
Added blue green domains to certificate
> fix: CLIN-334 Added blue green domains to certificate

- qa/apps/clin-ui/deployments.yml
- qa/apps/clin-ui/kustomization.yaml
- qa/apps/clin-ui/service.yml
- qa/fluxcd/clin-ui.yml
- qa/fluxcd/kustomization.yaml
Added clin ui and disabled frontend updates
> feat: CLIN-447 Added clin ui and disabled frontend updates

- qa/apps/certificate/certificate.yml
- qa/apps/frontend-dev/deployments.yml
- qa/apps/frontend-dev/ingresses.yml
- qa/apps/frontend-dev/kustomization.yaml
- qa/apps/frontend-dev/services.yml
- qa/fluxcd/frontend-dev.yml
- qa/fluxcd/kustomization.yaml
> feat: CLIN-447 Clin dev frontend integration

- qa/apps/frontend-dev/ingresses.yml
Added redirection path for clin ui static resources
> feat: CLIN-447 Added redirection path for clin ui static resources

- qa/apps/frontend/deployments.yml
rollback frontend to last known stable version
> feat: CLIN-447 rollback frontend to last known stable version

- qa/fluxcd/frontend-dev.yml
Removed suspend from clin dev frontend
> feat: CLIN-447 Removed suspend from clin dev frontend

- qa/fluxcd/arranger.yml
> feat: CLIN-509 Fixed arranger repo name

- qa/fluxcd/keycloak.yml
- staging/fluxcd/keycloak.yml
Temporarily disabled kustomization health checks on keycloak
> CLIN-574 Temporarily disabled kustomization health checks on keycloak

- qa/apps/fhir-server/configmaps-override.yml
Added override for legacy fhir server
> feat: CLIN-574 Added override for legacy fhir server

- qa/apps/frontend-dev/deployments.yml
- qa/apps/frontend/deployments.yml
- staging/apps/frontend/deployments.yml
Add front-end prescription renderer url env var.
> feat: CLIN-528 - add RENDERER_SERVICE_URL

- staging/apps/arranger/kustomization.yaml
- staging/apps/ferload/kustomization.yaml
- staging/apps/fhir-console/kustomization.yaml
- staging/apps/fhir-server/kustomization.yaml
- staging/apps/frontend/kustomization.yaml
- staging/apps/keycloak/kustomization.yaml
- staging/apps/proxy-api/kustomization.yaml
Re-enabling services for staging deployment
> feat: CLIN-574 Re-enabling services for staging deployment

- qa/apps/fhir-server/service-override.yml
- qa/apps/spark-jobs/raw-panels-etl/job.yml
- staging/apps/cleanup-jobs/delete-tables/delete-tables.yml
TBC 
- changes done during staging deployment
> feat: CLIN-687 - reviews during release

- staging/apps/fhir-server/backups/backup.yml
- staging/apps/fhir-server/backups/kustomization.yaml
- staging/apps/fhir-server/kustomization.yaml
Re-enabled fhir staging backups
> INFRA-6 Re-enabled fhir staging backups
